/**
 * Stand-in for `virtual:seemore/routes`, aliased in `vitest.config.ts`.
 *
 * The real module is generated by the Vite plugin and replaced wholesale on every content
 * change; this one exposes that replacement as a plain function so a test can drive the
 * corpus without a running server.
 */
import type { RouteEntry } from '../../src/shared/types.js';

let routes: RouteEntry[] = [];
const listeners = new Set<() => void>();

export function getRoutes(): RouteEntry[] {
  return routes;
}

export function subscribeRoutes(listener: () => void): () => void {
  listeners.add(listener);
  return () => {
    listeners.delete(listener);
  };
}

/** Replace the route list the way a rebuilt virtual module does. Does not notify. */
export function setRoutes(next: RouteEntry[]): void {
  routes = next;
}
